# Generated by Django 5.1.7 on 2025-04-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0002_alter_mentorados_foto_disponibilidadehorarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorados',
            name='token',
            field=models.UUIDField(default=None, unique=True),
        ),
    ]
