# Generated by Django 5.1.7 on 2025-04-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0003_mentorados_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorados',
            name='token',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
